name: 'semantic-release'
description: 'Configures and execute semantic-release'

inputs:
  assets:
    default: "CHANGELOG.md"
    description: |
      Comma separated list of assets to commit with release.
    required: false
  debug:
    default: "false"
    description: |
      Activates semantic-release debug log
    required: false
  default-branch:
    default: "main"
    description: |
      Default branch of project.
    required: false
  dev-version-schema:
    default: generic
    description: |
      Defines development version schema to fit to artifact version rules.
      Options:
        - generic
        - npm
        - python
      
      # generic
      - Uses SemVer 2.0.0 with build postfix.
      - Connects version with postfix by "+".
      - Replaces "/", "_", "@" in branch name with "-".
      - Example: v1.2.3+feat-version-numbers
      
      # npm
      - Uses SemVer 2.0.0 with pre-release postfix. npm doesn't support SemVer 2.0 version with build postfix.
      - Replaces "/", "_", "@" in branch name with "-".
      - Example: v1.2.3-3-feat-version-numbers
      
      # python
      - Uses dev postfix with additional timestamp. Python doesn't support SemVer 2.0.0 postfixes.
      - Connects version with postfix by ".".
      - Doesn't use branch name.
      - Example v1.2.3.3dev20240423113359
    required: false
  package-name:
    default: ""
    description: |
      `package-name` is used when creating git tag with `@semantic-release/git`.
      If empty no prefix will be set.
      Supports mono repository usage.
    required: false
  step:
    default: "prepare"
    description: |
      Options:
        - prepare
        - release
    required: false
  working-directory:
    default: ${{ github.workspace }}/.semantic-release
    description: |
      Working directory to checkout semantic-release files.
    required: false

outputs:
  version:
    description: |
      Actual version for branch.
      Empty if no releasable state exists.
  version-file:
    description: |
      File path to file with actual version for branch.
      Empty if no releasable state exists.
  release-version:
    description: |
      Next release version.
      Empty if no releasable state exists.
  release-version-file:
    description: |
      File path to file with next release version.
      Empty if no releasable state exists.
  dev-version:
    description: |
      Next release version.
      Empty if no releasable state exists.
  dev-version-file:
    description: |
      File path to file with next release version. 
      Empty if no releasable state exists.

runs:
  using: node20
  main: dist/main/index.js