name: Release
on:
  push:
    branches:
      - '**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.release_ssh_key }}

      - name: npm install
        shell: bash
        run: |
          npm install

      - name: lint
        shell: bash
        run: |
          npm run lint

      - name: build dist files
        shell: bash
        run: |
          npm run build

      - name: semantic-release - prepare
        uses: ./
        id: semantic-release
        with:
          step: prepare
          debug: true

      - name: Print version outputs
        shell: bash
        run: |
          echo "Version: ${{ steps.semantic-release.outputs.version }}"
          echo "Version file path: ${{ steps.semantic-release.outputs.version-file }}"
          echo "Version file content: $(cat ${{ steps.semantic-release.outputs.version-file }})"
          echo "release-Version: ${{ steps.semantic-release.outputs.release-version }}"
          echo "release-Version file path: ${{ steps.semantic-release.outputs.release-version-file }}"
          echo "release-Version file content: $(cat ${{ steps.semantic-release.outputs.release-version-file }})"
          echo "dev-Version: ${{ steps.semantic-release.outputs.dev-version }}"
          echo "dev-Version file path: ${{ steps.semantic-release.outputs.dev-version-file }}"
          echo "dev-Version file content: $(cat ${{ steps.semantic-release.outputs.dev-version-file }})"

      - name: semantic-release - release
        uses: ./
        if: ${{ github.ref == format('{0}/{1}','refs/heads',github.event.repository.default_branch) }}
        with:
          step: release
          assets: "CHANGELOG.md,dist/**/*"
          debug: true
